version: '3.8'

services:
  personalfinances.presentation.webapi:
    image: ${DOCKER_REGISTRY-}personalfinancespresentationwebapi
    build:
      context: .
      dockerfile: src/PersonalFinances.Presentation.WebApi/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017 
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" 
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
