name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        networks:
          - app_network

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    - name: Set up Docker Compose environment
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Wait for MongoDB to be ready
      run: |
        until docker exec mongodb nc -z localhost 27017; do
          echo "Waiting for MongoDB..."
          sleep 2
        done

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal
